language: node_js
node_js: '13'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install --frozen-lockfile --ignore-engines
jobs:
  fast_finish: true
  include:
    - stage: Test
      node_js: '13'
      script: yarn run test -u
      after_script: |
        git push -a -m 'ci: Fix.'
    - stage: Build
      node_js: '13'
      script: yarn run build
    - stage: Release
      if: branch = master
      node_js: '13'
      before_deploy:
        - git config --global user.name ${GITHUB_USER}
        - git config --global user.email ${GITHUB_EMAIL}
        - git remote set-url origin
          "https://${GITHUB_TOKEN}@github.com/rajzik/conventional-changelog-beemo.git" > /dev/null
          2>&1
        - git checkout master
        - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      deploy:
        provider: script
        script: yarn run release
        skip_cleanup: true
        on:
          branch: master
notifications:
  email: false
cache:
  yarn: true
