name: Pull request check

on:
  pull_request:
    branches:
      - master

jobs:
  pull_request_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install --frozen-lockfile --ignore-engines
      - run: yarn danger ci --use-github-checks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_FAKE_CI: GitHub
          DANGER_TEST_REPO: oriflame/conventional-changelog-tools
          DANGER_TEST_PR: ${{ github.event.number }}
